### ISSUE TITLE
Can't compile for any arduino board?

### ISSUE THREAD

**Issue by Akirakato1** [TMRh20/AutoAnalogAudio#13]
TMRpcm couldn't compile for Arduino micro (just using to test your libraries first) but I get error ```fastadc:50:21: error: 'class TMRpcm' has no member named 'startRecording'``` same for stopRecording. So I turned to try AAAudio. Both libraries were installed by searching inside Arduino ide library manager. I tried running the SimpleADCStream example but get error ```C:\Users\AKIRA~1.KAT\AppData\Local\Temp\ccK7SMga.ltrans0.ltrans.o: In function `__vector_13':

C:\Users\akira.kato\Documents\Arduino\libraries\AutoAnalogAudio\src\avr/AutoAnalogAudio.cpp:212: undefined reference to `DACC_Handler()'

collect2.exe: error: ld returned 1 exit status ```. I try setting board to Arduino nano to try to just compile since it saids in wiki it works but the compilation failed for same error.

**Comment by TMRh20** [comment]
With TMRpcm the recording functions are enabled by editing the pcmConfig.h file. You should not get that error unless you are attempting to use them without being enabled.

With Aaaudio, the sketches are designed for Arduino Due, so modifications may be needed for AVR devices. Add the following near the top of your sketch:

void DACC_Handler(void) {};

For some reason the Due realizes when the above function is not used, but AVR devices need it to be defined always.
