### ISSUE TITLE
Missing declaration of variable adcChannel on AutoAnalogAudio.h

### ISSUE THREAD

**Issue by fernandoeqc** [TMRh20/AutoAnalogAudio#19]
Hello .. I tried to build an example, but I got the following output: 'error:' **adcChannel** 'was not declared in this scope'.
I declared the **adcChannel** variable in the **AutoAnalogAudio.h** header, so the compilation was completed without errors.

**Comment by TMRh20** [comment]
Which example and what board are you building with?

**Comment by TMRh20** [comment]
Thanks for posting this, I see it was a problem with the last release. Fixed in the newest release which should be available in 24 hours in the Arduino IDE.
