### ISSUE TITLE
 AutoAnalogAudio

### ISSUE THREAD

**Issue by FoxEast2021** [TMRh20/AutoAnalogAudio#20]
Hi Mr
Is AutoAnalogAudio work with esp32 boards?
And if it works, with what kind of esp32 board's?

**Comment by TMRh20** [comment]
Any esp32 that uses the Arduino framework and has DAC/ADC pins exposed.

**Comment by MRcode2102** [comment]
Can you tell me if this board works with your library please?

https://github.com/Nicholas3388/LuaNode

**Comment by 2bndy5** [comment]
That link is for the SDK to run a LUA interpreter on a ESP32/8266 based board. It does not demonstrate using the Arduino IDE (which uses c++). Lua is an entirely different programming language than C++.

Please provide a store link to the board you bought.

**Comment by FoxEast2021** [comment]
https://www.amazon.co.uk/AZDelivery-NodeMcu-CP2102-Development-including/dp/B071P98VTG/ref=asc_df_B071P98VTG/?tag=googshopuk-21&linkCode=df0&hvadid=430764102847&hvpos=&hvnetw=g&hvrand=13195359199711610181&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=2826&hvtargid=pla-367709801435&psc=1&tag=&ref=&adgrpid=108575012108&hvpone=&hvptwo=&hvadid=430764102847&hvpos=&hvnetw=g&hvrand=13195359199711610181&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=2826&hvtargid=pla-367709801435

at this above link Mr 2bndy5

can you suggest to me an esp 32 board to handling the AutoAnalogAudio library?

**Comment by 2bndy5** [comment]
It should work with most esp32 boards (including that esp32 dev board) as long as the board has analog input pins (ADC) and analog output pins (DAC). The Arduino framework that TMRh20 mentioned [needs to be installed](https://github.com/espressif/arduino-esp32#installation-instructions) for the Arduino IDE; it should support most esp32 by default.
