### ISSUE TITLE
Record sound from esp-cam

### ISSUE THREAD

**Issue by hyansuper** [TMRh20/AutoAnalogAudio#23]
Is it possible to stream not only video but also audio with esp-cam? 

Esp-cam has pinout gpio12 ~ gpio14 that can do adc ，but these pins are of adc2，and i2s driver seems to be hard coded with adc1

[This article](https://microcontrollerslab.com/adc-esp32-measuring-voltage-example/) says adc2 is use by WiFi on esp dev board，I guess it likely the same with esp-cam

esp-cam pinout and schematic
https://randomnerdtutorials.com/esp32-cam-ai-thinker-pinout/

That's too deep for me. I wonder if you are interested and have time to look into this question

**Comment by TMRh20** [comment]
I don't think so
