### ISSUE TITLE
How Pin use to record audio on esp32 in AAAudio library?

### ISSUE THREAD

**Issue by sekpona1** [TMRh20/AutoAnalogAudio#24]
Good evening everyone. I want to use the library https://github.com/TMRh20/AutoAnalogAudio on ESP32. But in the program I don't know where to define my microphone input. And so I don't know where to connect it to the esp board. Please help me.

**Comment by TMRh20** [comment]
See https://tmrh20.github.io/AutoAnalogAudio/classAutoAnalog.html#ab0f3ceccd76b77c0a6e407ba92f42346
