### ISSUE TITLE
Use on new Nano33BLE format boards

### ISSUE THREAD

**Issue by RivetingTiger** [TMRh20/AutoAnalogAudio#25]
G'day

I have been looking for a solution to play one and two word audio/pcm files from flash memory on the Nano33BLE board with no luck. The many solutions for this on other Arduino format boards don't work on the Nano33BLE. 

Is there a solution with this player that someone can help me with?

**Comment by TMRh20** [comment]
Nope, aaaudio doesn’t support this board.
