### ISSUE TITLE
Low / Distorted Input and Output

### ISSUE THREAD

**Issue by beankonducta** [TMRh20/AutoAnalogAudio#26]
Hi!

Using an Arduino Nano clone with the library. Reading in audio from a keyboard (Casio Sk-1) at line level. Inputting to A0 and outputting to 9 as per docs.

Audio is successfully being read in and output through DAC to a 4ohm speaker and a rca output, but the audio is extremely distorted. Here's the wave being read in:

![Untitled](https://user-images.githubusercontent.com/12212978/132550158-f876b86a-34cd-41d0-a20f-bc2a93c03e6d.png)

I tried using a PAM8403 breakout for amplification in but it didn't output anything useful. Still getting relatively low levels in.

When I plug into a power amp via rca it's EXTREMELY loud and distorted.

Thanks for help & for the wonderful library!

and simple code to recreate:

```#include <AutoAnalogAudio.h>

AutoAnalog aaAudio;
void DACC_Handler(void) {
  aaAudio.dacHandler();
}

void setup() {

  pinMode(A3, OUTPUT);
  digitalWrite(A3, HIGH);

  Serial.begin(115200);

  aaAudio.begin(1, 1);
  aaAudio.autoAdjust = 1;
  aaAudio.dacBitsPerSample = 8;
  
  aaAudio.getADC(32);
}

void loop() {

  aaAudio.feedDAC(0, 32);
  aaAudio.getADC(32);

  for (int i = 0; i < 32; i++) {
    aaAudio.dacBuffer[i] = aaAudio.adcBuffer[i] << 2;
    Serial.println(aaAudio.dacBuffer[i]);
  }
}

**Comment by TMRh20** [comment]
It might just be a matter of lowering the level of the input signal, but you could also try adjusting the MAX_BUFFER_SIZE in AutoAnalog_config.h then using the new value (say 96 or so) in your calls to feedDac and getAdc.
