### ISSUE TITLE
I can't make it stream over radio nrf24l01.

### ISSUE THREAD

**Issue by Raduq91** [TMRh20/AutoAnalogAudio#28]
Tried with pro micro and teensy 2.0, esp32 firebeetle, atmega2560.
Tried  WirelessMicrophone, WirelessSpeaker.I put a microphone on the sender pin A0(I could see the signal with the oscilloscope) and probed all the pins on the receiver and nothing.
(attachInterrupt(digitalPinToInterrupt(4), RX, FALLING); does not work, there is no signal activity on the nrf24l01 pins; I put RX(); in loop and I see activity)

I used SimpleSine example on the sender(I could see the signal on the sender pins 9,10), uncommented lines to enable radio, probed all pins on the receiver and nothing.

Simple radio example hello world works.

**Comment by TMRh20** [comment]
Depending on what you want to do, there is also my RF24Audio library, which streams audio on AVR devices, and is much simpler to use than AAAudio.

If that doesn't work for your plans, then with AAAudio, there are a couple things to consider:
1. The AAAudio library was designed on Arduino Due, so all the examples are designed for the Due as well. They may require modifications to work on AVR devices and ESP32.
2. The wireless microphone and wireless speaker sketches are not designed to work together. They probably should be but aren't. This is on the list to fix.
3. I'll see if I can throw together an example sketch that works on AVR devices for you, at least with the simple sine example, so you have a starting point. Not sure how soon I can get to it, so let me know if this will be necessary. I noticed some issues last time I used it with AVR devices, so I think something may have gotten screwed up in AVR support. I'll have to test a bit...
4. ESP32 support is still buggy and I haven't had time to really dig into it.

**Comment by Raduq91** [comment]
I tried RF24Audio too and it was the same.

I tried the normal library nRF24L01 with the teensy audio and it works.But there is a bit of latency(I think because of the teensy audio library) and there are rare random audio pops.
So I wanted to try different options to see how it is with the latency and audio pops.

**Comment by TMRh20** [comment]
One thing u may want to try with teensy audio is creating an audio ramp that ramps the signal from 0 to the value of the first audio signal and at the end from the Val. Of the last audio signal to 0. That may clear up the popping. 
Else I would suggest trying again with rf24audio. The library is functional and works, so it’s likely just a wiring or config issue you are having. Then if that is working, you can mess around with AAAudio and it should be easier to get working at that point.
