### ISSUE TITLE
Playback problem

### ISSUE THREAD

**Issue by Robak08** [TMRh20/AutoAnalogAudio#3]
Hi,
tried to use ur library to output number generated wav file, but can't get it to work. There is no playback sound at all. SDAudioBasics example working just fine (with that switch operator). I'm using Arduino Uno, here's code I'm using - basically generate random number up to 27 (which is last file on sd card -> "27.wav"), then checks if sensor value is above limit, if so the playback should occur. Thanks in advance.

`
#include <SPI.h>
#include <SD.h>
#include <AutoAnalogAudio.h>
AutoAnalog aaAudio;
void DACC_Handler(void) {
  aaAudio.dacHandler();
}
int input = A4;
int output = 8;
int val = 0;
void setup() {
  Serial.begin(115200);
  randomSeed(analogRead(A5));
  pinMode(input, INPUT);
  pinMode(output, OUTPUT);
  if (!SD.begin(10)) {
    Serial.println("SD fail");
    return;
  }
  else {
    Serial.println("SD ok");
  }
  aaAudio.begin(0, 1);
  aaAudio.autoAdjust = 0;
  aaAudio.dacBitsPerSample = 8;
  aaAudio.setSampleRate(16000);
}
void loop() {
  val = analogRead(input);
  char buffer[10];
  char buffer2[20];
  int rand = random(1, 28);
  sprintf(buffer, "%d.wav", rand);
  sprintf(buffer2, "Status sensora: %d", val);
  Serial.println(buffer2);
  if (val > 10) {
        digitalWrite(output, HIGH);
        delay(500);
        Serial.println(buffer); //debug
        playAudio(buffer);
        } else {
        delay(500);
        digitalWrite(output, LOW);
    }
  loadBuffer();
}
File myFile;
void playAudio(char *audioFile){
  if (myFile) {
  myFile.close();
  }
  myFile = SD.open(audioFile);
  myFile.seek(44);
  loadBuffer();
  }
void loadBuffer(){
  if(myFile.available()){
    for(int i=0;i<32;i++){
      aaAudio.dacBuffer[i] = myFile.read();
    }
    aaAudio.feedDAC(0,32);
  }
}`

**Comment by PabloRigo** [comment]
Me pasa lo mismo.
