### ISSUE TITLE
Does the library Support Audio recording on an STM32 Board/Architecture

### ISSUE THREAD

**Issue by JoelMuhanguzi** [TMRh20/AutoAnalogAudio#30]
Hello, in my project I am trying to record sound onto an SD card using an STM32F4 microcontroller, I am wondering whether this library has support for the STM32 architecture in order to do this. Any help/ advice rendered will be greatly appreciated.

**Comment by TMRh20** [comment]
Sorry, I thought I answered this a long time ago, but no, STM32 is not supported
