### ISSUE TITLE
Example Confusion of hardware definition

### ISSUE THREAD

**Issue by killamorri07** [TMRh20/AutoAnalogAudio#31]
https://github.com/TMRh20/AutoAnalogAudio/blob/cbc4d6dc1d1bb7caede5f9881bddb0981bbef0b8/examples/SDAudio/SdAudioRecording/SdAudioRecording.ino#L100

Hi, I'm new to Arduino.

My goal is to continues recording using buffer for long hours without the need to play wav files. Currently, I'm trying to test your code in my Arduino Due, MicroCard adapter and MAX9814. I understand 85% of it and try to create my own version however all the example seems to has been modify for ESP32. 
1) Seems like example of ESP32 in **_AutoAnalogAudio/examples/SDAudio/SdAudioRecording/_**  has adcbuffer while older version of this example did not called this function. This confused me.

2) The example in  **_AutoAnalogAudio/examples/SDAudio/SdAudioRecording/_** also have stopRecording function that are far different than this version. I assume this also related to adcbuffer.

**Comment by TMRh20** [comment]
Yes, the recent changes were made to support the ESP32, although ESP32 support is still buggy. The library works best with the Arduino Due.
Wherever it says `#if defined (ESP32)` you can safely remove that chunk of code.

**Comment by killamorri07** [comment]
Okay thank you
