### ISSUE TITLE
Problem with ADC read

### ISSUE THREAD

**Issue by alazka8** [TMRh20/AutoAnalogAudio#34]
Hi,  I used your lib and have some problem with adc :)
I used it with adcChannel = ADC1_CHANNEL_5; and I need get value from analogRead(36).
When program comes to line with analogread it freeze.
I try adc1_get_raw(ADC1_CHANNEL_0) and still the same.
Is there any way to use lib and read value from ADC1_CHANNEL_0 ?

**Comment by TMRh20** [comment]
AutoAnalogAudio does its own thing with the ADC, so if you are trying to use it separately that may cause problems. I don't have a solution for you, but there is probably a way to manually disable the ADC functionality of AAAudio. It depends on what board you are using.

**Comment by alazka8** [comment]
I need record from ADC1 channel5 and get value from ADC1 channel0 at the same time. I use esp32 wrover

**Comment by alazka8** [comment]
> AutoAnalogAudio does its own thing with the ADC, so if you are trying to use it separately that may cause problems. I don't have a solution for you, but there is probably a way to manually disable the ADC functionality of AAAudio. It depends on what board you are using.

I have esp32 wrover, I need record from adc1_channel_5 and read value from adc1_channel_0 at the same time ;//

**Comment by alazka8** [comment]
> > AutoAnalogAudio does its own thing with the ADC, so if you are trying to use it separately that may cause problems. I don't have a solution for you, but there is probably a way to manually disable the ADC functionality of AAAudio. It depends on what board you are using.
> 
> I have esp32 wrover, I need record from adc1_channel_5 and read value from adc1_channel_0 at the same time ;//

:) Can you tell me how to disable it manually ?

**Comment by TMRh20** [comment]
Sorry for the late reply, must have missed this one. I don't know the answer, and ESP32 support is still pretty buggy/in development.
