### ISSUE TITLE
Compile error for ESP32-S3

### ISSUE THREAD

**Issue by plidauer** [TMRh20/AutoAnalogAudio#35]
Hey there!

Whenever I try to compile even the basic examples included in this library for my ESP32-S3 (Adafruit Feather ESP32-S3 TFT) I get the following error. I'm no pro with Arduino and C/++ in general and I can't really pinpoint the error source, but I think it could be related to the ESP32-S3 being rather new and this lib maybe not updated yet?

```
libraries/AutoAnalogAudio/src/AutoAnalogAudio.h:235:3: error: 'adc1_channel_t' does not name a type; did you mean 'i2s_channel_t'?
   adc1_channel_t adcChannel;
   ^~~~~~~~~~~~~~
```

Cheers!
Philipp

**Comment by TMRh20** [comment]
You seem to be on the right track, I also think its because the ESP32-S3 is new/different and the library will need modifications to work with it. That being said, regular ESP32 support is still very buggy and not recommended for use other than testing etc.
