### ISSUE TITLE
max 9814 record

### ISSUE THREAD

**Issue by alazka8** [TMRh20/AutoAnalogAudio#36]
Hi, is there any solution how to record from max 9814? I try record by this mic, but recorded file is so distorted and indistinct.

**Comment by TMRh20** [comment]
What board are you using to record with?

Have you tried adjusting the gain etc?

**Comment by alazka8** [comment]
Hi, the problem was in adjusting the parameters like sampleRate, byteRate etc. I change it and it start recording. Now all is ok but record file is little faster than normal :) but i'm on good way to resolve this :)
