### ISSUE TITLE
Recording speed

### ISSUE THREAD

**Issue by Geethukulal** [TMRh20/AutoAnalogAudio#37]
Iam using AutoAnalogAudio library for Audio Recording using esp32 but my audio recording speed is too fast is there is  any solution for that

**Comment by TMRh20** [comment]
What board are u using?Typically you can just adjust the sample rate to fine tune playback speedOn May 18, 2023, at 3:33 AM, Geethukulal ***@***.***> wrote:﻿
Recording speed is too fast is there is  any solution for that

**Comment by Geethukulal** [comment]
Iam using ESP32 Board,  if i record 10 sec audio in memory card it will show 2 min of recording

**Comment by TMRh20** [comment]
I hate to say it, but ESP32 support is very buggy right now. I should probably remove it for now, but in any case, I need to do a bunch of work on the library to solve your problem.

**Comment by Geethukulal** [comment]
Okey,

**Comment by Geethukulal** [comment]
Can i use max9814 microphone to record audio

**Comment by TMRh20** [comment]
Yeah that's what I typically use

**Comment by Geethukulal** [comment]
How can i connect it

**Comment by Geethukulal** [comment]
For which pin of esp32 board  i connect out pin of max9814

**Comment by TMRh20** [comment]
It depends on the board, but whichever pin is A0 or Analog pin 0 in the Arduino platform
