### ISSUE TITLE
problems with esp32

### ISSUE THREAD

**Issue by predomaquilare** [TMRh20/AutoAnalogAudio#40]
sup guys, i was trying to record some stuff with a old mic module and the esp32 module by itself, with sd card. but im having this problem when i send de record option to serial monitor, as you can see below
![imagem_2024-02-12_200421925](https://github.com/TMRh20/AutoAnalogAudio/assets/104324993/52f1092f-3061-4491-8066-a43584b25c6e)

im using the sdaudiorecording.ino example, an esp32 regular board and an analog mic
by the way sorry for the bad english :(

**Comment by TMRh20** [comment]
There is an example included specifically for the ESP32, but even that doesn't work very well. I don't think recording is really possible on the ESP32 without glitches, so I've kind of abandoned that code and have considered removing it from the library since I can't get it working properly.
